// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleCatalogMVCAssignment.Models;

namespace VehicleCatalogMVCAssignment.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleCatalogMVCAssignment.Models.Vehicle", b =>
                {
                    b.Property<int>("VinNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAutomaticTransmission")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleClassClassId")
                        .HasColumnType("int");

                    b.HasKey("VinNo");

                    b.HasIndex("VehicleClassClassId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VehicleCatalogMVCAssignment.Models.VehicleCategory", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassId");

                    b.ToTable("VehicleCategories");
                });

            modelBuilder.Entity("VehicleCatalogMVCAssignment.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleCatalogMVCAssignment.Models.VehicleCategory", "VehicleClass")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleClassClassId");
                });
#pragma warning restore 612, 618
        }
    }
}
